### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by ryanxinrui** [haoyuanz13/Deep_Learning#1]
您好 请问如何用自己的数据集测试呢

**Comment by haoyuanz13** [comment]
训练参考CUFS的格式，而且数据集需要匹配，因为这个是paired数据训练而不是像cycleGAN一样。

**Comment by haoyuanz13** [comment]
> 您好 请问如何用自己的数据集测试呢

训练参考CUFS的格式，而且数据集需要匹配，因为这个是paired数据训练而不是像cycleGAN一样
